name: CI Pipeline

on:
  push:
    branches:
      - main
      - dev-app
  pull_request:
    branches:
      - main
      - dev-app

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner le code
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Installer JDK et Maven
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Install local library
        run: |
          mvn install:install-file -Dfile=libs/StrategiesLib_G2_5-1.0-SNAPSHOT.jar \
          -DgroupId=org.example -DartifactId=StrategiesLib_G2_5 \
          -Dversion=1.0-SNAPSHOT -Dpackaging=jar
          mvn install:install-file -Dfile=libs/G2_10/strategies_g2_10.jar \
          -DpomFile=libs/G2_10/pom.xml

      - name: Build and run tests
        run: |
          mvn clean package
        

      # Étape 3 : Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Étape 4 : Build Docker image
      - name: Build Docker image
        run: |
          docker build -t badzim/codelands:dpr-server-latest -f docker/Dockerfile .
          docker tag badzim/codelands:dpr-server-latest badzim/codelands:dpr-server-v${{ github.run_number }}

      # Étape 5 : Push Docker image
      - name: Push Docker image
        run: |
          docker push badzim/codelands:dpr-server-latest
          docker push badzim/codelands:dpr-server-v${{ github.run_number }}
            # Étape 1 : Configurer SSH

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Étape 7 : Exécuter le script de mise à jour sur le serveur
      - name: Deploy to production
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_LOGIN }}@${{ secrets.SERVER_IP }} "/root/codelands/dpr/server/update.sh"